### ISSUE TITLE
USB_OTG_HS missing from STM32H7R7A8Ix and STM32H7S7Z8Jx in CubeMX

### ISSUE THREAD

**Issue by doesnotcompete** [STMicroelectronics/STM32Cube_MCU_Overall_Offer#38] opened 2024-09-21 22:33 UTC
Hello,
while implementing [USB support for the H7R/S series within Embassy](https://github.com/embassy-rs/embassy/pull/3337) we have noticed that the CubeMX database is missing a definition for the `USB_OTG_HS` IP block for the STM32H7R7A8Ix and STM32H7S7Z8Jx. 

It is therefore also impossible to configure this peripheral within CubeMX, although both the ST website and CubeMX indicate those devices should also have HS USB with an integrated PHY:
![image](https://github.com/user-attachments/assets/798c8d41-fa2d-4e95-a211-3605eac05011)

**Comment by ALABSTM** [comment] 2024-09-23 10:54
ST Internal Reference: 191796

**Comment by ALABSTM** [comment] 2024-09-23 10:56
Hi @doesnotcompete,

Thank you for the heads-up. Your report has been logged internally to be considered for future versions of the `STM32CubeMX` tool.

With regards,

**Comment by ALABSTM** [comment] 2024-10-03 17:03
Hi @doesnotcompete,

Our hardware design team confirmed none of `STM32H7R7A8Ix` and `STM32H7S7Z8Jx` part numbers implement `USB OTG HS`. It looks like the issue is rather due to what is indicated on [st.com](https://www.st.com/en/microcontrollers-microprocessors/stm32h7r7a8.html).

With regards,

**Comment by ALABSTM** [comment] 2024-10-14 11:01
Hi @doesnotcompete,

I hope you are doing well. As already communicated, none of `STM32H7R7A8Ix` and `STM32H7S7Z8Jx` part numbers implement `USB OTG HS`, only `USB OTG FS`.

The information available on _st.com_ has been updated. Please allow me to close this issue. Our apology for any inconvenience. Thank you for your comprehension.

With regards,

**Closed by ALABSTM** 2024-10-14 11:01 UTC
Labels: bug, invalid, internal bug tracker, cube mx, usb
